export const GET_ERRORS="GET_ERRORS";
export const GET_PROJECT_TASKS="GET_PROJECT_TASKS";
export const GET_PROJECT_TASK="GET_PROJECT_TASK";
export const DELETE_PROJECT_TASKS="DELETE_PROJECT_TASKS";
export const GET_MODULE_TASKS="GET_MODULE_TASKS";
 export const GET_MODULE_TASK="GET_MODULE_TASK";
 export const DELETE_MODULE_TASKS="DELETE_MODULE_TASKS";
 export const GET_DEFECT_TASKS="GET_DEFECT_TASKS";
 export const GET_DEFECT_TASK="GET_DEFECT_TASK";
 export const DELETE_DEFECT_TASKS="DELETE_DEFECT_TASKS";



// export default {
//     GET_ERRORS,
//     GET_PROJECT_TASKS
// }